contact_links:  
  - name: Discussions
    url: https://github.com/esensar/neovim-java/discussions
    about: Please ask and answer questions here, as well as discuss potential improvements and ideas.
