pipeline:
  prepare-credentials:
    image: alpine:latest
    secrets:
      - maven_central_username
      - maven_central_token
    commands:
      - echo '<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd"><servers><server><id>ossrh</id><username>'$${MAVEN_CENTRAL_USERNAME}'</username><password>'$${MAVEN_CENTRAL_TOKEN}'</password></server></servers></settings>' > settings.xml
    when:
      event: tag

  publish:
    image: eclipse-temurin:17-jdk-alpine
    secrets:
      - maven_gpg_private_key
      - maven_gpg_passphrase
    commands:
      - apk add gpg
      - echo $MAVEN_GPG_PRIVATE_KEY | gpg --import
      - ./mvnw clean source:jar javadoc:aggregate-jar javadoc:jar verify gpg:sign deploy -DskipTests -Dgpg.passphrase=$MAVEN_GPG_PASSPHRASE -P release -s settings.xml
    when:
      event: tag
