pipeline:
  test:
    image: eclipse-temurin:17-jdk-alpine
    commands:
      - ./mvnw clean source:jar javadoc:aggregate-jar javadoc:jar verify gpg:sign deploy -DskipTests -P release

when:
  event: tag
