pipeline:
  prepare-credentials:
    image: robertstettner/drone-mvn-auth
    settings:
      servers:
        - id: ossrh
          username:
            from-secret: MAVEN_CENTRAL_USERNAME
          password:
            from-secret: MAVEN_CENTRAL_TOKEN

  publish:
    image: eclipse-temurin:17-jdk-alpine
    commands:
      - ./mvnw clean source:jar deploy -DskipTests
    when:
      event: push

branches: main
