pipeline:
  prepare-credentials:
    image: alpine:latest
    secrets:
      - MAVEN_CENTRAL_USERNAME
      - MAVEN_CENTRAL_TOKEN
    commands:
      - echo '<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd"><servers><server><id>ossrh</id><username>'$${MAVEN_CENTRAL_USERNAME}'</username><password>'$${MAVEN_CENTRAL_TOKEN}'</password></server></servers></settings>' > settings.xml
    when:
      event: push

  publish:
    image: eclipse-temurin:17-jdk-alpine
    commands:
      - ./mvnw clean source:jar deploy -DskipTests -s settings.xml
    when:
      event: push

branches: main
