name: Mark stale issues and pull requests

on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/stale@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue is stale because it has been open 60 days with no activity. Please consider closing it.'
          stale-pr-message: 'This pull request is stale because it has been open 60 days with no activity. Please consider closing it.'
          stale-issue-label: 'stale'
          stale-pr-label: 'stale'
          days-before-close: -1
          days-before-stale: 60
